/********************************************************************
* /home/inutini/irene_thesis/G4_Analysis/G4HadStudies/src/ProdTuple_tDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/inutini/irene_thesis/G4_Analysis/G4HadStudies/src/ProdTuple_tDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableProdTuple_tDict();
extern void G__cpp_setup_inheritanceProdTuple_tDict();
extern void G__cpp_setup_typetableProdTuple_tDict();
extern void G__cpp_setup_memvarProdTuple_tDict();
extern void G__cpp_setup_globalProdTuple_tDict();
extern void G__cpp_setup_memfuncProdTuple_tDict();
extern void G__cpp_setup_funcProdTuple_tDict();
extern void G__set_cpp_environmentProdTuple_tDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/inutini/irene_thesis/G4_Analysis/G4HadStudies/include/ProdTuple_t.hh"
#include "/home/inutini/irene_thesis/G4_Analysis/G4HadStudies/include/TrackInfo_t.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ProdTuple_tDictLN_TClass;
extern G__linked_taginfo G__ProdTuple_tDictLN_TBuffer;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMemberInspector;
extern G__linked_taginfo G__ProdTuple_tDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_ProdTuple_t;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ProdTuple_tDictLN_TVector3;
extern G__linked_taginfo G__ProdTuple_tDictLN_TLorentzVector;
extern G__linked_taginfo G__ProdTuple_tDictLN_TrackInfo_t;

/* STUB derived class for protected member access */
